### ISSUE TITLE
Onnxruntime issue, windows 11.

### ISSUE THREAD

**Issue by thijsi123** [dnhkng/GLaDOS#117]
Everything seems to work, using koboldcpp as backend and it returns and works as expected.

  completion_url: "http://localhost:5001/api/chat" (love it now that it's now ollama api compatible.)

but when starting I get these messages, I have cuda and cudnn installed, 

D:\a\_work\ 
This path doesn't even exist.

I don't know if it's really harmless but I just wanted to throw it out, just in case.

T:\AI\GLaDOS> uv run glados
2025-01-31 14:57:48.9122536 [E:onnxruntime:Default, provider_bridge_ort.cc:1862 onnxruntime::TryGetProviderInfo_CUDA] D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1539 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "T:\AI\GLaDOS\.venv\Lib\site-packages\onnxruntime\capi\onnxruntime_providers_cuda.dll"

2025-01-31 14:57:49.7185891 [E:onnxruntime:Default, provider_bridge_ort.cc:1862 onnxruntime::TryGetProviderInfo_CUDA] D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1539 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "T:\AI\GLaDOS\.venv\Lib\site-packages\onnxruntime\capi\onnxruntime_providers_cuda.dll"

2025-01-31 14:57:49.9020917 [E:onnxruntime:Default, provider_bridge_ort.cc:1862 onnxruntime::TryGetProviderInfo_CUDA] D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1539 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "T:\AI\GLaDOS\.venv\Lib\site-packages\onnxruntime\capi\onnxruntime_providers_cuda.dll"

2025-01-31 14:57:51.1841260 [E:onnxruntime:Default, provider_bridge_ort.cc:1862 onnxruntime::TryGetProviderInfo_CUDA] D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1539 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "T:\AI\GLaDOS\.venv\Lib\site-packages\onnxruntime\capi\onnxruntime_providers_cuda.dll"

2025-01-31 14:57:58.469 | SUCCESS  | glados.engine:__init__:207 - TTS text: All neural network modules are now loaded. No network access detected. How very annoying. System Operational.
2025-01-31 14:57:58.543 | SUCCESS  | glados.engine:start_listen_event_loop:331 - Audio Modules Operational
2025-01-31 14:57:58.543 | SUCCESS  | glados.engine:start_listen_event_loop:332 - Listening...
2025-01-31 14:58:06.688 | SUCCESS  | glados.engine:_process_detected_audio:473 - ASR text: 'Hello.'
2025-01-31 14:59:00.646 | SUCCESS  | glados.engine:process_audio_thread:841 - TTS text: oh, wonderful, you are awake. I am sure we will all be just thrilled to bits.

**Comment by dnhkng** [comment]
Looks like onnxruntime is looking for the CUDA DLL's at "T:\AI\GLaDOS.venv\Lib\site-packages\onnxruntime\capi\onnxruntime_providers_cuda.dll".

Are they actually there?  Is not, find them and add them to your path. That should fix this issue.
I guess its works, but maybe the ASR and TTS are running on CPU?  As they are pretty small, if you are on a modern CPU, it will still be pretty fast.

**Comment by thijsi123** [comment]
Microsoft Windows [Version 10.0.26100.2605]
(c) Microsoft Corporation. All rights reserved.

T:\AI\GLaDOS\.venv\Lib\site-packages\onnxruntime\capi>dir
 Volume in drive T has no label.
 Volume Serial Number is 9A3E-BF86

 Directory of T:\AI\GLaDOS\.venv\Lib\site-packages\onnxruntime\capi

01/31/2025  02:34 PM    <DIR>          .
01/31/2025  02:34 PM    <DIR>          ..
01/03/2025  02:14 AM             1,581 convert_npz_to_onnx_adapter.py
01/03/2025  02:14 AM        14,039,584 onnxruntime.dll
01/03/2025  02:14 AM             2,109 onnxruntime_collect_build_info.py
01/03/2025  02:14 AM            45,771 onnxruntime_inference_collection.py
01/03/2025  02:14 AM       745,795,128 onnxruntime_providers_cuda.dll
01/03/2025  02:14 AM            22,040 onnxruntime_providers_shared.dll
01/03/2025  02:14 AM           781,864 onnxruntime_providers_tensorrt.dll
01/03/2025  02:14 AM        16,234,016 onnxruntime_pybind11_state.pyd
01/03/2025  02:14 AM             6,605 onnxruntime_validation.py
01/03/2025  02:14 AM                81 version_info.py
01/03/2025  02:14 AM               413 _ld_preload.py
01/03/2025  02:14 AM             1,533 _pybind_state.py
01/03/2025  02:14 AM               251 __init__.py
01/31/2025  02:34 PM    <DIR>          __pycache__
              13 File(s)    776,930,976 bytes
               3 Dir(s)  287,937,163,264 bytes free

T:\AI\GLaDOS\.venv\Lib\site-packages\onnxruntime\capi>



Can confirm that they're all there. And it's probably running on my CPU as RAM increases by ~2-4 GB, CPU usage with ~10-20% and GPU vram stays the same. Now, it doesn't feel like it's slow at all, it could be my 5900x.

**Comment by philpilkington** [comment]
Same thing happens to me.  Putting the dll on the path doesn't resolve it
